### ISSUE TITLE
java.lang.NoSuchMethodError: No static method

### ISSUE THREAD

**Issue by ericntd** [airbnb/Showkase#113]
The crash:
```
2020-10-20 15:09:13.677 19942-19942/com.example.composedesigndemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.composedesigndemo, PID: 19942
    java.lang.NoSuchMethodError: No static method Scaffold-tiGujGI(Landroidx/compose/ui/Modifier;Landroidx/compose/material/ScaffoldState;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function3;Lkotlin/jvm/functions/Function2;Landroidx/compose/material/FabPosition;ZLkotlin/jvm/functions/Function3;Landroidx/compose/ui/graphics/Shape;FJJJJJLkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/material/ScaffoldKt; or its super classes (declaration of 'androidx.compose.material.ScaffoldKt' appears in /data/app/com.example.composedesigndemo-N8mZJ-OmTeglUTramA5Y0w==/base.apk)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt.ShowkaseBrowserApp(ShowkaseBrowserApp.kt:40)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserActivity$onCreate$1.invoke(ShowkaseBrowserActivity.kt:37)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserActivity$onCreate$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:113)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt:105)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.AndroidAmbientsKt.ProvideAndroidAmbients(AndroidAmbients.kt:97)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Wrapper.kt:269)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt:268)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2703)
        at androidx.compose.runtime.Composer.composeInitial(Composer.kt:1867)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:243)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:115)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:262)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:562)
        at android.view.View.dispatchAttachedToWindow(View.java:19553)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2028)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
2020-10-20 15:09:13.677 19942-19942/com.example.composedesigndemo E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

The only set of components I have:
```
const val THE_GROUP = "CTA"
val buttonTextPrimary = TextStyle(color = Color.White, fontWeight = FontWeight.Bold)

@Composable
fun cta(variant: String, text: String) {
    when (ButtonType.valueOf(variant)) {
        ButtonType.PRIMARY -> {
            primaryButton(text)
        }
        ButtonType.DANGEROUS -> {
            dangerousButton(text)
        }
        ButtonType.SECONDARY -> {
            secondaryButton(text)
        }
        ButtonType.POSITIVE -> {
            positiveButton(text)
        }
        ButtonType.HYPER_LINK -> {
            hyperlink(text)
        }
    }
}

@Composable
@Preview(name = "hyperlink", group = THE_GROUP)
fun hyperlink(@PreviewParameter(ButtonTextProvider::class) text: String) {
    val containerModifier = Modifier
    val textStyle = TextStyle(color = colorPrimary, fontWeight = FontWeight.Bold)
    Box(modifier = containerModifier.padding(32.dp, 16.dp, 32.dp, 16.dp)) {
        Text(text, style = textStyle)
    }
}

@Composable
@Preview(name = "secondary", group = THE_GROUP)
fun positiveButton(@PreviewParameter(ButtonTextProvider::class) text: String) {
    val containerModifier = Modifier.clip(RoundedCornerShape(50))
        .background(Color.Green)
        .wrapContentHeight()
    Box(modifier = containerModifier.padding(32.dp, 16.dp, 32.dp, 16.dp)) {
        Text(text, style = buttonTextPrimary)
    }
}

@Composable
@Preview(name = "secondary", group = THE_GROUP)
fun secondaryButton(@PreviewParameter(ButtonTextProvider::class) text: String) {
    val containerModifier = Modifier.border(1.dp, colorPrimary, RoundedCornerShape(50))
    Box(modifier = containerModifier.padding(32.dp, 16.dp, 32.dp, 16.dp)) {
        Text(text)
    }
}

@Composable
@Preview(name = "dangerous", group = THE_GROUP)
fun dangerousButton(@PreviewParameter(ButtonTextProvider::class) text: String) {
    val containerModifier = Modifier.clip(RoundedCornerShape(50))
        .background(Color.Red)
        .wrapContentHeight()
    Box(modifier = containerModifier.padding(32.dp, 16.dp, 32.dp, 16.dp)) {
        Text(text, style = buttonTextPrimary)
    }
}

@Composable
@Preview(name = "primary", group = THE_GROUP)
fun primaryButton(@PreviewParameter(ButtonTextProvider::class) text: String) {
    val containerModifier = Modifier.clip(RoundedCornerShape(50))
        .background(colorPrimary)
        .wrapContentHeight()
    Box(modifier = containerModifier.padding(32.dp, 16.dp, 32.dp, 16.dp)) {
        Text(text, style = buttonTextPrimary)
    }
}
```

Any ideas?

**Comment by vinaygaba** [comment]
Can you try compiling it against `alpha02` version of compose. I suspect it's probably because of incompatibility between the version of compose you are using vs the one the library uses. 

I'm bumping up the library version tomorrow night so this should be a temporary issue.

**Comment by ericntd** [comment]
Thanks but all versions before `alpha05` seems to be not found for me
```
Execution failed for task ':app:prepareDebugKotlinCompileTask'.
> Could not resolve all files for configuration ':app:kotlin-extension'.
   > Could not find androidx.compose.compiler:compiler:1.0.0-alpha03.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/compiler/compiler/1.0.0-alpha03/compiler-1.0.0-alpha03.pom
       - https://jcenter.bintray.com/androidx/compose/compiler/compiler/1.0.0-alpha03/compiler-1.0.0-alpha03.pom
     Required by:
         project :app
```
Not sure if I'm doing anything wrong

**Comment by vinaygaba** [comment]
Can you try this `androidx.compose:compose-compiler:1.0.0-alpha02`. If this works, it's because if you notice carefully, the artifact group id's are slightly different. `androidx.compose:compose-compiler` vs `androidx.compose.compiler:compiler`

**Comment by vinaygaba** [comment]
I think it's because the group id's are slightly different between alpha02 and alpha05. Let me do a release today and that might be the least painful way to fix your problem. I'll ping you here once I do the release!

**Comment by vinaygaba** [comment]
@ericntd Can you try the latest release of this library. Hopefully that should fix the problem

```
implementation "com.airbnb.android:showkase:1.0.0-alpha03"
kapt "com.airbnb.android:showkase-processor:1.0.0-alpha03"
```

**Comment by ericntd** [comment]
Works like a charm, thanks a lot @vinaygaba 👏

**Comment by vinaygaba** [comment]
Glad to hear that!
