### ISSUE TITLE
java.lang.NoSuchMethodError: No static method setContent

### ISSUE THREAD

**Issue by yektasarioglu** [airbnb/Showkase#123]
I'm using `1.0.0-alpha08` version which is the same compose version as the library. Any ideas on how to solve it?
```kotlin
java.lang.NoSuchMethodError: No static method setContent$default(Landroidx/activity/ComponentActivity;Landroidx/compose/runtime/Recomposer;Lkotlin/jvm/functions/Function2;ILjava/lang/Object;)Landroidx/compose/runtime/Composition; in class Landroidx/compose/ui/platform/WrapperKt; or its super classes (declaration of 'androidx.compose.ui.platform.WrapperKt' appears in /data/app/com.yektasarioglu.testapp.debug-ZwvsZzo9Jrsy4DLjhICVeg==/base.apk)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserActivity.onCreate(ShowkaseBrowserActivity.kt:26)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by vinaygaba** [comment]
@yektasarioglu If you try the latest version of Showkase `alpha04`, it should fix the issue. Also use the latest version of compose that just launched (`alpha09`). This combination should def fix the issue in my opinion. Let me know if you observe otherwise.

**Comment by yektasarioglu** [comment]
@vinaygaba I encountered [this compiler error](https://issuetracker.google.com/issues/176046527) after upgrading to `alpha09`. That's why I can't even build the project for the testing. I would share the result as soon as I test it. Thank you for getting back to me.

**Comment by vinaygaba** [comment]
@yektasarioglu Yeah I recently bumped up Showkase to use the latest version of compose. Unfortunately, compose versions aren't compatible among each other so you will have to upgrade your compose version to `alpha09` :( I have no control over that unfortunately as that is a compose compatibility issue.

**Comment by yektasarioglu** [comment]
I did but I still got the same compiler error :/

**Comment by vinaygaba** [comment]
@yektasarioglu Okay let me take a deeper look at this and see if I can repro. Is the stack trace identical? Were you using any other compose libraries like navigation, paging, accompanist, etc?

**Comment by yektasarioglu** [comment]
Accompanist is the only compose library that I use at the moment.

**Comment by vinaygaba** [comment]
@yektasarioglu And are you using this version - https://github.com/chrisbanes/accompanist/releases/tag/v0.4.1
Because the older version of Accompanist will not work with compose `alpha09`

**Comment by yektasarioglu** [comment]
Yes. I did upgrade Accompanist to the latest `0.4.1` version and unfortunately still getting this compiler issue.

**Comment by vinaygaba** [comment]
@yektasarioglu So I just tested it on an existing project and I did not encounter this issue. Try to invalidate the cache and build again and if that doesn't work either, could you publish your project on github so that I can take a look.

**Comment by yektasarioglu** [comment]
@vinaygaba I tried almost any tricks to get a successful build so that I can test it but it seems to be a Compose compiler issue rather than any other libraries. There are already [three open issues](https://issuetracker.google.com/issues?q=java.lang.AssertionError:%20CALL%20%27public%20final%20fun%20%3Cget-currentComposer%3E%20():%20androidx.compose.runtime.Composer%3C*%3E%20declared%20in%20androidx.compose.runtime.ComposerKt%27%20type%3Dandroidx.compose.runtime.Composer%3C*%3E%20origin%3DFOR_LOOP_ITERATOR.) about it. I also created another **Empty Compose Activity** from templates to simulate this issue on a new project as well. And this issue is fixed but the other project which I got this experiencing this compose compiler issue whatever I try. Thanks, Vinay for your efforts 👍

**Comment by igorwojda** [comment]
I am observing this as well with `1.0.0-beta07`. This fixed the issue for me

```
// app Gradle file
android
{
	...
	buildFeatures {
    	compose true
	}
}
```
