### ISSUE TITLE
NoSuchMethodError: No static method Text

### ISSUE THREAD

**Issue by StephanSchuster** [airbnb/Showkase#154]
When launching showcase I get the following crash. I am using compose beta 09 since I cannot use beta 08 due to other reasons. Is this crash because showkase is not yet compatible with compose 09 or am I doing something wrong. The stacktrace does not make much sense to me. I would assume Text should be available in either version, right?

Thanks for helping.

`
java.lang.NoSuchMethodError: No static method Text-6FffQQw(Ljava/lang/String;Landroidx/compose/ui/Modifier;JJLandroidx/compose/ui/text/font/FontStyle;Landroidx/compose/ui/text/font/FontWeight;Landroidx/compose/ui/text/font/FontFamily;JLandroidx/compose/ui/text/style/TextDecoration;Landroidx/compose/ui/text/style/TextAlign;JLandroidx/compose/ui/text/style/TextOverflow;ZILkotlin/jvm/functions/Function1;Landroidx/compose/ui/text/TextStyle;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/material/TextKt; or its super classes (declaration of 'androidx.compose.material.TextKt' appears in /data/app/com.example.demo-ZeBUS3UgHK5iiyUWfoVzew==/base.apk)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt.ToolbarTitle(ShowkaseBrowserApp.kt:177)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt.ShowkaseAppBarTitle(ShowkaseBrowserApp.kt:152)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt.ShowkaseAppBar(ShowkaseBrowserApp.kt:91)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt$ShowkaseAppBar$2.invoke(Unknown Source:8)
        at com.airbnb.android.showkase.ui.ShowkaseBrowserAppKt$ShowkaseAppBar$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2156)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2399)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2578)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:523)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2564)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2540)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:613)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:764)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:103)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:447)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

**Comment by vinaygaba** [comment]
You are right! This is because of Compose still not offering binary compatibility just yet. I'll be bumping up compose and doing a release later today. That should fix the crash you are seeing.

**Comment by StephanSchuster** [comment]
Thank you. I am looking forward to the "alpha-12" release.

**Comment by vinaygaba** [comment]
https://github.com/airbnb/Showkase/releases/tag/1.0.0-alpha12 is ready for use!

**Comment by StephanSchuster** [comment]
Thanks. Will try it out immediately.
