### ISSUE TITLE
Kapt always fails with ClassNotFoundException

### ISSUE THREAD

**Issue by xatok** [airbnb/Showkase#157]
I'm trying to integrate Showkase in a compose project as a separate Android app module, and I consistently get this error every time I build the project:

```
Caused by: java.lang.ClassNotFoundException: androidx.compose.runtime.Composable
	at com.airbnb.android.showkase.processor.ShowkaseProcessor.init(ShowkaseProcessor.kt:58)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:41)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:175)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:686)
	... 41 more
```

I made sure to be using the save versions for `compose`, `compose-activity`, `compose-navigation` and `compose-constraintlayout`. Have tried to disable many other dependencies that might be causing the issue with kapt, but at this point I'm not sure what else to try.

Versions:
```
showkase = "1.0.0-alpha12"
compose = "1.0.0-beta09"
composeConstraintlayout = "1.0.0-alpha07"
composeActivity = "1.3.0-beta02"
composeNavigation = "2.4.0-alpha03"
```

**Comment by vinaygaba** [comment]
I'm curious about why you are trying to integrate it as a separate Android project as opposed to the library directly? Will be hard to debug this without seeing your setup.

**Comment by vinaygaba** [comment]
Also can you try with the latest version of the library that was release yesterday. It supports the latest version of compose!

**Comment by vinaygaba** [comment]
Just encountered this issue and have pushed a fix for it! @xatok
