### ISSUE TITLE
Provided Metadata instance has version 2.1.0, while maximum supported version is 2.0.0.

### ISSUE THREAD

**Issue by dostalleos** [airbnb/Showkase#400]
After updating Kotlin to version 2.1.0, I can't build the project. I'm getting 
```
java.lang.IllegalArgumentException: Provided Metadata instance has version 2.1.0, 
while maximum supported version is 2.0.0. To support newer versions, update the kotlinx-metadata-jvm library.
``` 
error.

Showkase SDK: 1.0.3

Full stack trace:
```
error: java.lang.IllegalArgumentException: Provided Metadata instance has version 2.1.0, while maximum supported version is 2.0.0. To support newer versions, update the kotlinx-metadata-jvm library.
  	at androidx.room.jarjarred.kotlinx.metadata.jvm.KotlinClassMetadata$Companion.throwIfNotCompatible$kotlinx_metadata_jvm(KotlinClassMetadata.kt:609)
  	at androidx.room.jarjarred.kotlinx.metadata.jvm.KotlinClassMetadata$Companion.checkMetadataVersionForRead(KotlinClassMetadata.kt:600)
  	at androidx.room.jarjarred.kotlinx.metadata.jvm.KotlinClassMetadata$Companion.read(KotlinClassMetadata.kt:579)
  	at androidx.room.compiler.processing.javac.kotlin.KmClassContainer$Companion.createFor(KotlinClassMetadataUtils.kt:184)
  	at androidx.room.compiler.processing.javac.JavacTypeElement$kotlinMetadata$2.invoke(JavacTypeElement.kt:62)
  	at androidx.room.compiler.processing.javac.JavacTypeElement$kotlinMetadata$2.invoke(JavacTypeElement.kt:61)
  	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  	at androidx.room.compiler.processing.javac.JavacTypeElement.getKotlinMetadata(JavacTypeElement.kt:61)
  	at androidx.room.compiler.processing.javac.JavacFieldElement$kotlinMetadata$2.invoke(JavacFieldElement.kt:54)
  	at androidx.room.compiler.processing.javac.JavacFieldElement$kotlinMetadata$2.invoke(JavacFieldElement.kt:53)
  	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  	at androidx.room.compiler.processing.javac.JavacFieldElement.getKotlinMetadata(JavacFieldElement.kt:53)
  	at androidx.room.compiler.processing.javac.JavacTypeElement$_declaredFields$2.invoke(JavacTypeElement.kt:117)
  	at androidx.room.compiler.processing.javac.JavacTypeElement$_declaredFields$2.invoke(JavacTypeElement.kt:107)
  	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  	at androidx.room.compiler.processing.javac.JavacTypeElement.get_declaredFields(JavacTypeElement.kt:107)
  	at androidx.room.compiler.processing.javac.JavacTypeElement.getDeclaredFields(JavacTypeElement.kt:133)
  	at androidx.room.compiler.processing.XTypeElement.getEnclosedElements(XTypeElement.kt:217)
  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.processCustomAnnotationFromClasspath(ShowkaseProcessor.kt:208)
  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.processComponentAnnotation(ShowkaseProcessor.kt:103)
  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.process(ShowkaseProcessor.kt:84)
  	at com.airbnb.android.showkase.processor.BaseProcessor.internalProcess(BaseProcessor.kt:95)
  	at com.airbnb.android.showkase.processor.BaseProcessor.process(BaseProcessor.kt:65)
  	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
  	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:216)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
  	at jdk.internal.reflect.GeneratedMethodAccessor1413.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:97)
  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:36)
  	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:46)
  	at jdk.internal.reflect.GeneratedMethodAccessor3602.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:325)
  	at org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction.execute(KaptWithoutKotlincTask.kt:266)
```

It looks like an issue in the Room library, but I haven't found any report about it.
I tried to remove Showkase from the project, and everything worked after that.

**Comment by dostalleos** [comment]
Any update here? 🙏  We can not update Kotlin version because of this issue.
